import { mkdirSync, readFileSync, readdirSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import type { RelationAst } from '../registry/calculator/lib/dsl/ast'
import { parseRelation } from '../registry/calculator/lib/dsl/parser'

export function parseLibraryMarkdown(markdown: string, filename: string) {
  const groups: { title: string; equations: { source: string; ast: RelationAst }[] }[] = []
  let title = filename.replace(/\.md$/i, '')
  // Headings group equations; dollar delimiters support inline and display math.
  const content = markdown.replace(/^```[^\n]*\n[\s\S]*?^```\s*$/gm, '')
  for (const match of content.matchAll(/^#{1,6}\s+(.+)$|\$\$([\s\S]*?)\$\$|\$([^$\n]+)\$/gm)) {
    if (match[1]) {
      title = match[1].trim()
      continue
    }
    const source = (match[2] ?? match[3]).trim()
    if (!source) continue
    let ast: RelationAst
    try {
      ast = parseRelation(source)
      if (ast.kind !== 'equation') throw new Error('Expected an equation with "=".')
    } catch (error) {
      throw new Error(`${filename} (${title}): ${source}: ${error instanceof Error ? error.message : error}`)
    }
    let group = groups.at(-1)
    if (!group || group.title !== title) {
      group = { title, equations: [] }
      groups.push(group)
    }
    group.equations.push({ source, ast })
  }
  return { file: filename, groups }
}

if (import.meta.main) {
  const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
  const folder = resolve(root, 'library')
  const library = readdirSync(folder, { withFileTypes: true })
    .filter((entry) => entry.isFile() && /\.md$/i.test(entry.name))
    .sort((a, b) => a.name.localeCompare(b.name))
    .map((entry) => parseLibraryMarkdown(readFileSync(resolve(folder, entry.name), 'utf8'), entry.name))
  const output = resolve(root, 'registry/calculator/lib/generated/equation-library.ts')
  mkdirSync(dirname(output), { recursive: true })
  await Bun.write(output, `// Generated by scripts/render-calculator-library.ts from library/*.md.\nimport type { RelationAst } from '@/registry/calculator/lib/dsl/ast'\n\nexport const EQUATION_LIBRARY: { file: string; groups: { title: string; equations: { source: string; ast: RelationAst }[] }[] }[] = ${JSON.stringify(library, null, 2)}\n`)
}
